
# ------------- Makefile options, which depens on OS --------------------------

VERSION		= 1.06.05

# what is used to delete files, compile, install and find
RM              = /bin/rm -f
MV              = /bin/mv -f
CP              = /bin/cp
LN              = /bin/ln -f
ECHO            = /bin/echo
CC              = gcc-4.1
CFLAGS          = -g -O0 -Wno-pointer-sign -fPIC -Wall -Wno-format-y2k -pthread  
LDLIBS          =  -lm   -pthread -lbluetooth  
SMSD_LIBS       = -L/usr/lib -lmysqlclient -lz -lcrypt -lnsl -lm
INSTALL         = /usr/bin/install
FIND            = /usr/bin/find
RPMBUILD        = /usr/bin/rpmbuild
DOXYGEN         = /usr/bin/doxygen
AR              = /usr/bin/ar
RANLIB          = /usr/bin/ranlib
FAKEROOT        = /usr/bin/fakeroot
CHECKINSTALL    = 

# where to install binary, documentation, man and shared library files
# where is temporary directory and directory for making RPM
prefix          = /usr
exec_prefix     = ${prefix}
INSTALL_BIN_DIR	= ${exec_prefix}/bin
INSTALL_DOC_DIR = ${prefix}/share/doc/gammu
INSTALL_LOC_DIR = ${prefix}/share/gammu
INSTALL_MAN_DIR = ${prefix}/man/man1
INSTALL_LIB_DIR = ${exec_prefix}/lib
INSTALL_H_DIR	= ${prefix}/include/gammu
RPM_DIR         = /usr/src/rpm
TEMP_DIR        = /tmp

CFLAGS         += -DLOCALE_PATH="\"${INSTALL_LOC_DIR}\""

# use these 2 in DJGPP:
# CFLAGS        = -Wall -Wno-format-y2k
# LDLIBS        = 
