#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:

# Usage: make-release [branch]

set -e

repo=python-gammu

version=`./setup.py --dump-config | sed -n 's/.*PYTHON_GAMMU_VERSION "\(.*\)"/\1/p' | tr -d '\n'`


tmp=`mktemp -dt $repo-build-XXXXXX`

cd $tmp
echo Working in $tmp
if [ "x$1" = "xbranch" ] ; then
    rel=RELEASE_`echo -n $version|tr . _`
    svn cp -m "Tag release $version" svn+ssh://mort/home/svn/$repo/trunk svn+ssh://mort/home/svn/$repo/tags/$rel
    svn export svn+ssh://mort/home/svn/$repo/tags/$rel $repo-$version
elif [ "x$1" = "x" ] ; then
    rel=trunk
    svn export svn+ssh://mort/home/svn/$repo/trunk $repo-$version
else
    version="$1"
    rel=RELEASE_`echo -n $version|tr . _`
    svn export svn+ssh://mort/home/svn/$repo/tags/$rel $repo-$version
fi

echo "Creating release $version from $rel"

cd $repo-$version

# Build source package
./setup.py sdist --formats=gztar,bztar,zip
mv dist/* ../

# Submit to PyPi
if [ "x$1" = "xbranch" ] ; then
    ./setup.py register
fi


# Windows distribution

./MakeFakeWin.sh i586-mingw32msvc

GAMMUVER=`ls -d ~/.wine/drive_c/Program\ Files/Gammu\ * | sort | tail -n 1 | sed 's/.* \([0-9.]*\)/\1/'`

wine c:\\python25\\python setup.py build_ext \
    --gammu-libs=c:\\Program\ Files\\Gammu\ $GAMMUVER\\lib \
    --gammu-incs=c:\\Program\ Files\\Gammu\ $GAMMUVER\\include\\gammu  \
    -c mingw32 \
    build bdist_wininst

wine c:\\python24\\python setup.py build_ext \
    --gammu-libs=c:\\Program\ Files\\Gammu\ $GAMMUVER\\lib \
    --gammu-incs=c:\\Program\ Files\\Gammu\ $GAMMUVER\\include\\gammu  \
    -c mingw32 \
    build bdist_wininst

mv dist/* ../

# We're done
echo "Release is in $tmp directory"
ls -lh $tmp
