.TH GAMMU-CONFIG "1" "May 2007" "Gammu configurator 0.3" "Gammu Documentation"
.SH NAME
gammu\-config \- Gammu configurator
.SH SYNOPSIS
.B gammu-config
[\fI\-f|\-\-force\fR] [\fI\-c|\-\-config config\fR]
.SH DESCRIPTION
Script to help configuring gammu.

These programs follow the usual GNU command line syntax, with long options
starting with two dashes (`\-'). A summary of options is included below.

.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-f, \-\-force
Force configuring even if config already exists.
.TP
.B \-c, \-\-config config
Define which configuration file to use.

.SH REPORTING BUGS
Please report bugs to <http://bugs.cihar.com>.

.SH SEE ALSO
gammu(1)
.SH COPYRIGHT
Copyright \(co 2003-2009 Michal Cihar and other authors.
License GPLv2: GNU GPL version 2 <http://www.gnu.org/licenses/old\-licenses/gpl\-2.0.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
