.TH GAMMU-CONFIG "1" "May 2007" "Gammu configurator 0.3" "Gammu Documentaion"
.SH NAME
gammu\-config \- Gammu configurator
.SH SYNOPSIS
.B gammu-config
[\fI\-f|\-\-force\fR] [\fI\-c|\-\-config config\fR]
.SH DESCRIPTION
Script to help configuring gammu.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`\-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-f, \-\-force
Force configuring even if config already exists.
.TP
.B \-c, \-\-config config
Define which configuration file to use.
.SH LICENCE
This program is licensed under GNU/GPL version 2.

.SH BUGS
There are definitely many bugs, reporting to author is welcome. Please include
some useful information when sending bug reports (eg. exception you received
and debug output). Please submit your reports to <http://bugs.cihar.com/>.

.SH SEE ALSO
gammu(1)
.SH COPYRIGHT
Copyright \(co 2003 - 2007 Michal Cihar <michal@cihar.com>
