.TH JADMAKER "1" "Jan 2008" "JAD File Generator" "Gammu Documentaion"
.SH NAME
jadmaker \- JAD File Generator
.SH SYNOPSIS
.B jadmaker
[\fI\-f|\-\-force\fR] [\fI\-u|\-\-url URL\fR]
<filename.jar>...
.SH DESCRIPTION
Script to generate JAD file from JAR file.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`\-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-f, \-\-force
Force rewriting of JAD file even if exists.
.TP
.B \-u, \-\-url URL
Define URL to be included in JAD file.
.SH LICENCE
This script is licensed under GNU/GPL version 2.

.SH BUGS
There are definitely many bugs, reporting to author is welcome. Please include
some useful information when sending bug reports (eg. exception you received
and debug output). Please submit your reports to <http://bugs.cihar.com/>.

.SH SEE ALSO
gammu(1)
.SH COPYRIGHT
Copyright \(co 2008 Michal Cihar <michal@cihar.com>
