//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Calendar.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_TBN_REPORT                  101
#define IDC_TBN_CARD                    102
#define IDC_TBN_ICON                    103
#define IDC_LIST                        104
#define ID_CONNECT                      105
#define IDC_TBN_LIST                    106
#define IDC_SCHEDULEDAYVIEW             107
#define IDC_OK                          108
#define ID_ORG_SCH_DELETE               109
#define ID_ORG_CALENDAR_DELETE          110
#define IDS_NOTETYPE_CALL               111
#define IDS_NOTETYPE_MEETING            112
#define IDS_NOTETYPE_BIRTHDAY           113
#define IDS_NOTETYPE_MEMO               114
#define IDS_NOTETYPE_REMIND             115
#define ID_ORG_SCH_ADD                  116
#define ID_ORG_SCH_EDIT                 119
#define IDC_STOP                        120
#define IDC_PROGRESS_BAR                121
#define IDC_START                       122
#define IDS_STOP                        123
#define IDS_CAL_ED_STARTTIME            124
#define IDR_MAINFRAME                   128
#define IDR_PHONEBTYPE                  129
#define IDR_TB_FUNC                     130
#define IDR_MAINFRAME_                  131
#define IDR_TB_TOOLBAR                  134
#define IDD_SEARCH                      136
#define IDD_DATA_BASE                   137
#define IDD_DATA_ADV                    138
#define IDD_DLG_PROG                    139
#define IDD_DATA_BASE2                  140
#define IDD_DATA_ADV2                   141
#define IDB_COLUMNHEADER_START          145
#define IDB_COLUMNHEADER_SPAN           146
#define IDB_COLUMNHEADER_END            147
#define IDR_TOOLBAR_LEFTHANDSIDE        180
#define IDR_TOOLBAR_RIGHTHANDSIDE       181
#define IDD_OPENREPEATQUESTDLG          181
#define IDB_SCH_MORE_GRAY               183
#define IDI_PHONE                       184
#define IDI_REMIND                      185
#define IDI_MEMO                        186
#define IDI_METTING                     187
#define IDI_BIRTHDAY                    188
#define IDI_ICON1                       189
#define IDD_DLG_TOPBAR                  190
#define IDB_BMP_TREEBK                  191
#define IDR_MENU_LISTRIGHTKEY           192
#define IDD_DLGBAR                      193
#define IDC_COMBO_NAME                  1000
#define IDC_BN_FINDNEXT                 1001
#define IDC_SC_ENTERNAME                1002
#define IDC_SC_TITLE                    1004
#define IDC_SC_FIRSTNAME                1005
#define IDC_SC_LASTNAME                 1006
#define IDC_SC_MOBILE                   1007
#define IDC_SC_COTEL                    1007
#define IDC_SC_GROUP                    1008
#define IDC_SC_MOBILENO                 1008
#define IDC_SC_SAVEPOS                  1009
#define IDC_SC_HOMETEL1                 1009
#define IDC_ED_FIRST                    1010
#define IDC_SC_HOMETEL2                 1010
#define IDC_ED_LAST                     1011
#define IDC_SC_EMAIL1                   1011
#define IDC_ED_MOBILE                   1012
#define IDC_SC_EMAIL2                   1012
#define IDC_CB_GROUP                    1013
#define IDC_SC_COFAX                    1013
#define IDC_SC_HOMEFAX                  1014
#define IDC_SC_OTHERFAX                 1015
#define IDC_BN_ADVANCE                  1016
#define IDC_SC_CARTEL                   1016
#define IDC_GROUP                       1017
#define IDC_SC_COMMERCETEL              1017
#define IDC_RD_SIM                      1018
#define IDC_SC_COMMERCETEL2             1018
#define IDC_RD_MOBILE                   1019
#define IDC_SC_BBCALL                   1019
#define IDC_SC_GROUPNAME                1020
#define IDC_SC_BRANCH                   1021
#define IDC_SC_COMPANY                  1022
#define IDC_SC_HANDLE                   1023
#define IDC_SC_COADDERSS                1024
#define IDC_SC_COZIP                    1025
#define IDC_SC_COTOWN                   1026
#define IDC_SC_HOMEADDRESS              1027
#define IDC_SC_HOMEZIP                  1028
#define IDC_SC_HOMETOWN                 1029
#define IDC_SC_COCITY                   1030
#define IDC_MEMO_DATA_TITLE             1030
#define IDC_SC_HOMECITY                 1031
#define IDC_MEMO_DATA_MEMO              1031
#define IDC_SC_COUNTRY                  1032
#define IDC_MEMO_LT_TITLE               1032
#define IDC_SC_WEBSET                   1033
#define IDC_MEMO_LT_MEMO                1033
#define IDC_SC_BETTERHALF               1034
#define IDC_SC_BIRTHDAY                 1035
#define IDC_SC_WEDDINGDAY               1036
#define IDC_ED_FIRSTNAME                1037
#define IDC_ED_LASTNAME                 1038
#define IDC_ED_COMPANYTEL               1039
#define IDC_ED_MOBILENO                 1040
#define IDC_ED_HOMETEL                  1041
#define IDC_ED_HOMETEL2                 1042
#define IDC_ED_EMAIL                    1043
#define IDC_ED_EMAIL2                   1044
#define IDC_ED_COMPANYFAX               1045
#define IDC_ED_HOMEFAX                  1046
#define IDC_ED_OTHERFAX                 1047
#define IDC_ED_CARTEL                   1048
#define IDC_ED_COMMERCETEL              1049
#define IDC_ED_COMMERCETEL2             1050
#define IDC_ED_BBCALL                   1051
#define IDC_CB_GROUPNAME                1052
#define IDC_ED_BRANCH                   1053
#define IDC_ED_COMPANY                  1054
#define IDC_ED_HANDLE                   1055
#define IDC_ED_COADDRESS                1056
#define IDC_ED_COZIP                    1057
#define IDC_ED_COCITY                   1058
#define IDC_ED_COTOWN                   1059
#define IDC_ED_HOMEADDRESS              1060
#define IDC_ED_HOMEZIP                  1061
#define IDC_ED_HOMECITY                 1062
#define IDC_ED_HOMETOWN                 1063
#define IDC_ED_COUNTRY                  1064
#define IDC_ED_WEBSET                   1065
#define IDC_ED_BETTERHALF               1066
#define IDC_CH_BIRTHDAY                 1067
#define IDC_CH_WEDDINGDAY               1068
#define IDC_DP_BIRTHDAY                 1069
#define IDC_DP_WEDDINGDAY               1070
#define IDC_PROG                        1070
#define IDC_SC_NAME                     1071
#define IDC_ED_NAME                     1072
#define IDC_SCH_LT_LOCATION             1074
#define IDC_SCH_LT_TYPE                 1076
#define IDC_SCH_DATA_NoteType           1077
#define IDC_SCH_CHK_TONE                1078
#define IDC_SCH_DATA_ALARMTIME          1081
#define IDC_STATIC_MESSAGE              1082
#define IDC_ST_1                        1083
#define IDC_SC_VERSION                  1083
#define IDC_ST_2                        1084
#define IDC_SC_COPYRIGHT                1084
#define IDC_SC_CAMVERSION               1085
#define IDC_LOG                         1086
#define IDC_STATIC_TITLE                1087
#define IDC_OPENCURRENTRADIO            1088
#define IDC_OPENSERIALRADIO             1089
#define IDC_RADIO1                      1090
#define IDC_SCH_DATA_STOPTIMETYPE       1092
#define IDC_SCH_DATA_ALARMTIMETYPE      1093
#define IDC_ANIMATE                     1093
#define IDC_REPEATENDSTATIC             1094
#define IDC_SC_DESCRIPTION              1095
#define IDC_ED_DESCRIPTION              1096
#define IDC_CHWEEK1                     1097
#define IDC_CHWEEK2                     1098
#define IDC_CHWEEK3                     1099
#define IDC_CHWEEK4                     1100
#define IDC_PVI_5_UE_SAVE               1101
#define IDC_CHWEEK5                     1101
#define IDC_PVI_5_UE_SAVEAS             1102
#define IDC_CHWEEK6                     1102
#define IDC_PVI_5_UE_DISCARD            1103
#define IDC_CHWEEK7                     1103
#define IDC_PVI_5_UE_MSG1               1104
#define IDC_SC_REPEATON                 1104
#define IDC_PVI_5_UE_CANCEL             1105
#define IDC_SC_REPEATE_INTERVAL         1105
#define IDC_SP_REPEATINTER              1107
#define IDC_ED_REPEATEINTER             1108
#define IDC_STC_CAL_PRIORITY            1109
#define IDC_CMB_CAL_PRIORITY            1110
#define IDC_SCH_LT_TITLE                1118
#define IDC_SCH_DATA_TITLE              1119
#define IDC_SCH_LT_STARTTIME            1120
#define IDC_SCH_DATA_STARTTIME          1121
#define IDC_SCH_LT_STOPTIME             1122
#define IDC_SCH_DATA_STOPTIME           1123
#define IDC_SCH_LT_MEMO                 1124
#define IDC_SCH_DATA_MEMO               1125
#define IDC_SCH_DATA_LOCATION           1126
#define IDC_SCH_GB_REPEAT_OPTION        1129
#define IDC_SCH_LT_REMIND_PHONENO       1132
#define IDC_SCH_DATA_ALARM_PHONENO      1133
#define IDC_SCH_DATA_STOPTIMEEDIT       1134
#define IDC_SCH_DATA_ALARMTIMEEDIT      1135
#define IDC_SCH_DATA_REPEAT_WHICHDATE   1139
#define IDC_ORG_MONTHCALENDAR           1142
#define IDC_SCH_DATA_STARTDATE          1142
#define IDC_SCH_CHK_ALARM               1143
#define IDC_SCH_DATA_ALARM_INTERVAL     1144
#define IDC_SCH_CHK_REPEAT              1145
#define IDC_SCH_CHK_REPEAT_Until        1146
#define IDC_SCH_DATA_REPEAT_TYPE        1147
#define IDC_SCH_LT_REPEAT_EVERY         1148
#define IDC_SCH_DATA_REPEAT_INTERVAL    1149
#define IDC_SCH_LT_REPEAT_INTERVALUNIT  1150
#define IDC_SCH_DATA_REPEAT_WHICHWEEK   1151
#define IDC_SCH_DATA_STOPDATE           1152
#define IDC_SCH_DATA_REPEAT_WEEKDAY     1153
#define IDC_SCH_DATA_BIRTHDAY           1154
#define IDC_SCH_DATA_ALARMDAY           1154
#define IDD_ORG_MEMO_EDITOR             11000
#define IDD_ORG_SCHEDULE_EDITOR         11001
#define IDD_ORG_SCHEDULE                11003
#define IDB_SCH_GOTOTODAY_BUTTON        11015
#define IDB_SCH_ALARM                   11016
#define IDB_SCH_ALARM_GRAY              11017
#define IDB_DATEPICKER_BUTTON           11018
#define IDB_SCH_REPEAT                  11028
#define IDB_SCH_REPEAT_GRAY             11029
#define IDB_SCH_MORE                    11030
#define IDD_PVI_5_USEREXIT              11037
#define ID_BN_PHONEBOOK                 32771
#define ID_BN_SCHEDULE                  32772
#define ID_BN_NEW                       32776
#define ID_BN_EDIT                      32777
#define ID_BN_DELETE                    32778
#define ID_BN_SEARCH                    32779
#define ID_BN_BACKUP                    32780
#define ID_BN_RESTORE                   32781
#define ID_BN_MEMO                      32782
#define ID_BN_REFRESH                   32783
#define ID_BN_EXIT                      32784
#define ID_BN_ABOUT                     32785
#define ID_BN_HELP                      32786
#define IDC_MENU_LIST_ADD               32788
#define IDC_MENU_LIST_EDIT              32789
#define IDC_MENU_LIST_DELETE            32790
#define IDC_MENU_LIST_REFLASH           32792
#define IDS_TITLE                       61204
#define IDS_PHONEBOOK                   61205
#define IDS_SCHEDULE                    61206
#define IDS_MEMO                        61207
#define IDS_ERR_LOADSKIN                61208
#define IDS_MOBILE_NO                   61209
#define IDS_MOBILE                      61210
#define IDS_SIMCARD                     61211
#define IDS_REPORT                      61212
#define IDS_CARD                        61213
#define IDS_ICON                        61214
#define IDS_COMPANYTEL                  61215
#define IDS_HOMETEL                     61216
#define IDS_MOBILETEL                   61217
#define IDS_PIC                         61218
#define IDS_NAME                        61219
#define IDS_TEL_NO                      61220
#define IDS_GROUP                       61221
#define IDS_DELONECONTACT               61222
#define IDS_DELCONTACTS                 61223
#define IDS_OK                          61224
#define IDS_FINDNEXT                    61225
#define IDS_SEARCH                      61226
#define IDS_ENTERNAME                   61227
#define IDS_ERR_SEARCH                  61228
#define IDS_NEWCONTRACT                 61229
#define IDS_EDITCONTRACT                61230
#define IDS_FIRSTNAME                   61231
#define IDS_LASTNAME                    61232
#define IDS_MOBILENO                    61233
#define IDS_SAVEPOS                     61234
#define IDS_ADVANCE                     61235
#define IDS_SAVE                        61236
#define IDS_CANCEL                      61237
#define IDS_ERR_SELITEM                 61238
#define IDS_COMPANYNO                   61239
#define IDS_HOMENO                      61240
#define IDS_HPMENO2                     61241
#define IDS_EMAIL                       61242
#define IDS_EMAIL2                      61243
#define IDS_COFAX                       61244
#define IDS_HOMEFAX                     61245
#define IDS_OTHERFAX                    61246
#define IDS_CARTEL                      61247
#define IDS_COMMERCETEL                 61248
#define IDS_COMMERCETEL2                61249
#define IDS_BBCALL                      61250
#define IDS_BRANCH                      61251
#define IDS_COMPANY                     61252
#define IDS_HANDLE                      61253
#define IDS_COADDRESS                   61254
#define IDS_ZIP                         61255
#define IDS_CITY                        61256
#define IDS_TOWN                        61257
#define IDS_HOMEADDRESS                 61258
#define IDS_COUNTRY                     61259
#define IDS_HOMEPAGE                    61260
#define IDS_BETTERHALF                  61261
#define IDS_BIRTHDAY                    61262
#define IDS_WEDDINGDAY                  61263
#define IDS_ERR_NONAME                  61264
#define IDS_ERR_OPEN                    61265
#define IDS_ERR_GETGROUP                61266
#define IDS_ERR_GETSPACE                61267
#define IDS_ERR_LOADCONTRACT            61268
#define IDS_ERR_NOSPACE                 61269
#define IDS_COMPUTER                    61271
#define IDS_ERR_DROPTOTREE              61272
#define IDS_CONNECTING                  61273
#define IDS_DISCONNECTED                61274

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
