#!/bin/sh
# Create series60-remote.sis

PYS60DIR=~/PythonForS60
VERSION=0.6.0
CURDIR=$PWD


mkdir tmp

cp *.py tmp/

cd $PYS60DIR

python2.5 $PYS60DIR/ensymble.py py2sis \
    --appname="Gammu S60 Remote" \
    --version=$VERSION \
    --lang=EN \
    --shortcaption="Gammu S60" \
    --caption="Gammu S60 Remote" \
    --vendor="Michal Cihar" \
    --caps=LocalServices+ReadUserData+WriteUserData+WriteUserData+NetworkServices+UserEnvironment \
    --icon="$CURDIR/icon.svg" \
    --verbose \
    $CURDIR/tmp \
    $CURDIR/gammu-s60-remote.sis

python2.5 $PYS60DIR/ensymble.py py2sis \
    --appname="Gammu S60 Remote" \
    --version=$VERSION \
    --lang=EN \
    --shortcaption="Gammu S60" \
    --caption="Gammu S60 Remote" \
    --vendor="Michal Cihar" \
    --caps=LocalServices+Location+ReadDeviceData+ReadUserData+WriteUserData+WriteUserData+NetworkServices+UserEnvironment \
    --icon="$CURDIR/icon.svg" \
    --verbose \
    $CURDIR/tmp \
    $CURDIR/gammu-s60-remote-sign.sis

cd $CURDIR

rm -rf tmp
