#!/bin/sh
# Create series60-remote.sis

VERSION=0.4.80

mkdir tmp

cp *.py tmp/

ensymble py2sis \
    --appname="Series60 - Remote" \
    --version=$VERSION \
    --lang=EN \
    --shortcaption="S60-Remote" \
    --caption="Series60 - Remote" \
    --caps=LocalServices+ReadUserData+WriteUserData+WriteUserData+NetworkServices+UserEnvironment \
    --icon="icon.svg" \
    --verbose \
    ./tmp \
    series60-remote.sis

rm -rf tmp
