# Copyright (c) 2008 - 2010 Lukas Hetzenecker <LuHe@gmx.at>

NUM_CONNECTED = 100
NUM_HELLO_REQUEST = 110
NUM_HELLO_REPLY = 111
NUM_QUIT = 120
NUM_PARTIAL_MESSAGE = 130

NUM_CONTACTS_REQUEST_HASH_ALL = 200
NUM_CONTACTS_REQUEST_HASH_SINGLE = 201
NUM_CONTACTS_REQUEST_COUNT = 202
NUM_CONTACTS_REQUEST_CONTACT = 204
NUM_CONTACTS_REQUEST_CONTACTS_ALL = 205
NUM_CONTACTS_REPLY_HASH_ALL = 210
NUM_CONTACTS_REPLY_HASH_SINGLE_START = 211
NUM_CONTACTS_REPLY_HASH_SINGLE_LINE = 212
NUM_CONTACTS_REPLY_HASH_SINGLE_END = 213
NUM_CONTACTS_REPLY_COUNT = 214
NUM_CONTACTS_REPLY_CONTACT_START = 220
NUM_CONTACTS_REPLY_CONTACT_LINE = 221
NUM_CONTACTS_REPLY_CONTACT_END = 222
NUM_CONTACTS_REPLY_CONTACTS_ALL_END = 223
NUM_CONTACTS_REPLY_CONTACT_NOT_FOUND = 224
NUM_CONTACTS_ADD = 230
NUM_CONTACTS_ADD_REPLY_ID = 231
NUM_CONTACTS_DELETE = 232
NUM_CONTACTS_CHANGE_ADDFIELD = 233
NUM_CONTACTS_CHANGE_REMOVEFIELD = 234

NUM_SYSINFO_REQUEST = 250
NUM_SYSINFO_REPLY_START = 260
NUM_SYSINFO_REPLY_LINE = 261
NUM_SYSINFO_REPLY_END = 262

NUM_LOCATION_REQUEST = 270
NUM_LOCATION_REPLY = 271
NUM_LOCATION_REPLY_NA = 272

NUM_DIAL = 280
NUM_HANGUP = 281

NUM_MESSAGE_SEND_REQUEST = 300
NUM_MESSAGE_SEND_REPLY_OK = 301
NUM_MESSAGE_SEND_REPLY_STATUS = 302
NUM_MESSAGE_SEND_REPLY_FAILURE = 303
NUM_MESSAGE_SEND_REPLY_RETRY = 304
NUM_SET_READ = 320
NUM_MESSAGE_DELETE = 321

NUM_MESSAGE_NEW = 350
NUM_MESSAGE_REQUEST = 351
NUM_MESSAGE_REPLY_LINE = 352
NUM_MESSAGE_REPLY_END = 353

NUM_MESSAGE_REQUEST_UNREAD = 370
NUM_MESSAGE_REPLY_UNREAD = 371

NUM_MESSAGE_REQUEST_LIST = 372
NUM_MESSAGE_REPLY_LIST = 373

NUM_MESSAGE_REQUEST_COUNT = 374
NUM_MESSAGE_REPLY_COUNT = 375

NUM_MESSAGE_REQUEST_ONE = 376
NUM_MESSAGE_REPLY_ONE = 377

NUM_CALENDAR_REQUEST_COUNT = 378
NUM_CALENDAR_REPLY_COUNT = 379

NUM_CALENDAR_REQUEST_HASH_ALL = 380
# NUM_CALENDAR_REQUEST_HASH_SINGLE = 381
NUM_CALENDAR_REQUEST_ENTRY = 382
NUM_CALENDAR_REQUEST_ENTRIES_ALL = 383
NUM_CALENDAR_REPLY_HASH_ALL = 384
# NUM_CALENDAR_REPLY_HASH_SINGLE_START= 385
# NUM_CALENDAR_REPLY_HASH_SINGLE_LINE= 386
# NUM_CALENDAR_REPLY_HASH_SINGLE_END= 387
NUM_CALENDAR_REPLY_ENTRIES_START = 388
NUM_CALENDAR_REPLY_ENTRY = 389
NUM_CALENDAR_REPLY_ENTRIES_END = 390
NUM_CALENDAR_REPLY_ENTRY_NOT_FOUND = 391
NUM_CALENDAR_ENTRY_ADD = 395
NUM_CALENDAR_ENTRY_ADD_REPLY = 396
NUM_CALENDAR_ENTRY_DELETE = 397
NUM_CALENDAR_ENTRY_CHANGE = 398
NUM_CALENDAR_ENTRY_CHANGE_REPLY_TIME = 399

NUM_INCOMING_CALL = 400

NUM_SCREENSHOT = 900
NUM_SCREENSHOT_REPLY = 901

NUM_DEBUG = 999

NUM_END_HEADER = chr(0x02)  # Start of Text
NUM_SEPERATOR = chr(0x1E)  # Record Separator
NUM_END_TEXT = chr(0x03)  # End of Text

PROTOCOL_VERSION = 1.6
