/* Do not edit this file manually.
   This file is autogenerated by windmc.  */

//
//  The values are 32 bit layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      C    - is the Customer code flag
//
//      R    - is a reserved bit
//
//      Code - is the facility's status code
//
//      Sev  - is the severity code
//
//           Success - 00
#define STATUS_SEVERITY_SUCCESS 0x0
//           Informational - 01
#define STATUS_SEVERITY_INFORMATIONAL 0x1
//           Warning - 02
#define STATUS_SEVERITY_WARNING 0x2
//           Error - 03
#define STATUS_SEVERITY_ERROR 0x3
//
//      Facility - is the facility code
//
//           System - 0000
#define FACILITY_SYSTEM 0x0
//           Runtime - 0002
#define FACILITY_RUNTIME 0x2
//           Stubs - 0003
#define FACILITY_STUBS 0x3
//           Io - 0004
#define FACILITY_IO_ERROR_CODE 0x4
//           Application - 0fff
//

 /* --------------------------------------------------------
 HEADER SECTION
*/



/* ------------------------------------------------------------------
 MESSAGE DEFINITION SECTION
*/
//
// MessageId: EVENT_CAT_SMSD
//
#define EVENT_CAT_SMSD (DWORD) 0x1

//
// MessageId: EVENT_CAT_GAMMU
//
#define EVENT_CAT_GAMMU (DWORD) 0x2

//
// MessageId: EVENT_CAT_SQL
//
#define EVENT_CAT_SQL (DWORD) 0x3

//
// MessageId: EVENT_MSG_ERROR
//
#define EVENT_MSG_ERROR (DWORD) 0xc0020100

//
// MessageId: EVENT_MSG_INFO
//
#define EVENT_MSG_INFO (DWORD) 0x20101

//
// MessageId: EVENT_MSG_NOTICE
//
#define EVENT_MSG_NOTICE (DWORD) 0x40020102

//
// MessageId: EVENT_MSG_SQL
//
#define EVENT_MSG_SQL (DWORD) 0x40020102

//
// MessageId: EVENT_MSG_GAMMU
//
#define EVENT_MSG_GAMMU (DWORD) 0x40020102

