

#undef VERSION

/* Define if want DEBUG info */
#undef DEBUG

#undef GSM_ENABLE_MBUS2
#undef GSM_ENABLE_FBUS2
#undef GSM_ENABLE_DLR3AT
#undef GSM_ENABLE_IRDA
#undef GSM_ENABLE_INFRARED
#undef GSM_ENABLE_AT
//alcabus
#undef GSM_ENABLE_ATBLUETOOTH
#undef GSM_ENABLE_DLR3BLUETOOTH

#undef GSM_ENABLE_CELLBROADCAST

#undef GSM_ENABLE_BACKUP

#undef GSM_ENABLE_6110_AUTHENTICATION

#undef GSM_ENABLE_N71_91INCOMINGINFO

#undef GSM_ENABLE_NOKIA6110
#undef GSM_ENABLE_NOKIA6510
#undef GSM_ENABLE_NOKIA7110
#undef GSM_ENABLE_NOKIA9110
#undef GSM_ENABLE_ATGEN
//alcatel

//develop

//enable_beep
