#!/bin/sh
indent -npro -kr -i8 -ts8 -sob -ss -ncs -cli8 -nbad \
    --line-length150 \
    --indent-label0 \
    --braces-on-if-line \
    --cuddle-else \
    --cuddle-do-while \
    --no-space-after-function-call-names \
    "$@"
