#!/bin/sh
echo gammu.po:
for x in locale/*/gammu.po  ; do 
    lang=`echo $x | sed 's@locale/\(.*\)/gammu.po@\1@'`
    echo -n "$lang: "
    msgfmt --statistics --check -o - $x > /dev/null
done
echo libgammu.po:
for x in locale/*/libgammu.po  ; do 
    lang=`echo $x | sed 's@locale/\(.*\)/libgammu.po@\1@'`
    echo -n "$lang: "
    msgfmt --statistics --check -o - $x > /dev/null
done
echo docs.po:
for x in locale/*/docs.po  ; do 
    lang=`echo $x | sed 's@locale/\(.*\)/docs.po@\1@'`
    echo -n "$lang: "
    msgfmt --statistics --check -o - $x > /dev/null
done
