#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:

if [ -z "$1" ] ; then
    echo "Usage: set-version VERSION"
    exit 1
fi

version=$1

do_replace() {
    sed "s/@VERSION@/$version/;" < $1 > $2
}

echo "Setting version to $version"

# Packaging
do_replace cmake/templates/gammu.spec.in gammu.spec
do_replace cmake/templates/description-pak.in description-pak

# CMakeLists.txt
sed -i "
    s/set (VERSION \"[^\"]*\"\\(.*\\))/set (VERSION \"$version\"\1)/; 
    " CMakeLists.txt
# python/setup.py
sed -i "s/VERSION = '[0-9.]*'/VERSION = '$version'/" python/setup.py

# Update ChangeLog
if ! grep -q " - $version" ChangeLog ; then
    sed -i -e '/^=========$/ a\
    ' -e '/^=========$/ a\
2009???? - '"$version"'
    ' ChangeLog
fi
