#!/bin/sh

usage ()
{
    echo Usage: `basename $0` ../originaldir >&2
    exit 2
}

if [ $# -lt 1 ]
then
    usage
fi

find . -type f -name '*.[ch]' -exec sed -i 's@[[:space:]]*$@@' {} \;
find . -type f -exec touch -r $1/{} {} \;
