.TH "mgnokiidev" "8" "May 27, 2001" "" "Gnokii"
.SH "NAME"
mgnokiidev \- links /dev/gnokii to a virtual modem
.SH "SYNOPSIS"
.B mgnokiidev \fI/dev/pts/?\fR

.SH "DESCRIPTION"
.PP 
.B mgnokiidev
is a tool from the Gnokii tool suite used to create the link /dev/gnokii that points to a pseudo\-tty (/dev/pts/?).

.PP 
It is called after 
.B gnokiid
has created a virtual modem that is attached to the pty.  It's operation is transparent under normal usage as gnokiid takes care of calling it when required.

.PP 
Since
.B mgnokiidev
must modifiy files in /dev, it must be either run as root or SUID root.  The latter is the preferred method.  Normally the 
.B mgnokiidev
binary is chmod 4750 and owned by root.gnokii.

.PP 
Gnokii
is a Linux/Unix tool suite and (eventually) modem/fax driver for Nokia mobile phones, released under the GPL.
.PP 
Gnokii
supports most phones from the 3810/8110 and 5110/6110 series, details including bugs specific to each series appear in the files Docs/README\-3810 and Docs/README\-6110 respectively.  

.SH "DIAGNOSTICS"
Various error messages are printed to STDERR.
.SH "BUGS"
.PP 
None reported.


.SH "AUTHOR"
Hugh Blemings <hugh@blemings.org> and Pavel Janik ml. <Pavel.Janik@suse.cz> are the authors of the
Gnokii tool suite.

This manual page was written by Erik Rossen <rossen@freesurf.ch>.

See also Docs/CREDITS from the Gnokii sources.
.SH "COPYING"
This program is distributed under the GNU Public License.

.SH "SEE ALSO"
gnokiid, gnokii
