# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ALL_INSTALL_TYPES "Full;Standard;Developer")
set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/runner/work/gammu/gammu;/home/runner/work/gammu/gammu/_build")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "gammu;library;smsd;headers;utils;manpages;docs;pkgconfig;symbian;examples;manual")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_DLLS_HIDDEN "TRUE")
set(CPACK_COMPONENT_DLLS_REQUIRED "TRUE")
set(CPACK_COMPONENT_DOCS_DESCRIPTION "User documentation in text files.")
set(CPACK_COMPONENT_DOCS_DISPLAY_NAME "User Documentation")
set(CPACK_COMPONENT_DOCS_GROUP "Documentation")
set(CPACK_COMPONENT_DOCS_INSTALL_TYPES "Standard;Developer;Full")
set(CPACK_COMPONENT_EXAMPLES_DESCRIPTION "Examples showing how to use Gammu, in PHP, Perl or C.")
set(CPACK_COMPONENT_EXAMPLES_DISPLAY_NAME "Examples Using Gammu")
set(CPACK_COMPONENT_EXAMPLES_GROUP "Documentation")
set(CPACK_COMPONENT_EXAMPLES_INSTALL_TYPES "Developer;Full")
set(CPACK_COMPONENT_GAMMU_DEPENDS "library")
set(CPACK_COMPONENT_GAMMU_DESCRIPTION "The gammu.exe program.")
set(CPACK_COMPONENT_GAMMU_DISPLAY_NAME "Gammu Application")
set(CPACK_COMPONENT_GAMMU_GROUP "Runtime")
set(CPACK_COMPONENT_GAMMU_INSTALL_TYPES "Standard;Developer;Full")
set(CPACK_COMPONENT_GROUP_DEVELOPMENT_DESCRIPTION "Headers and documentation used for development using Gammu.")
set(CPACK_COMPONENT_GROUP_DOCUMENTATION_DESCRIPTION "Gammu documentation and usage examples.")
set(CPACK_COMPONENT_GROUP_RUNTIME_DESCRIPTION "Programs and libraries for general usage.")
set(CPACK_COMPONENT_HEADERS_DEPENDS "library")
set(CPACK_COMPONENT_HEADERS_DESCRIPTION "C headers for development own programs using Gammu library.")
set(CPACK_COMPONENT_HEADERS_DISPLAY_NAME "C Headers")
set(CPACK_COMPONENT_HEADERS_GROUP "Development")
set(CPACK_COMPONENT_HEADERS_INSTALL_TYPES "Developer;Full")
set(CPACK_COMPONENT_LIBRARY_DESCRIPTION "Gammu library.")
set(CPACK_COMPONENT_LIBRARY_DISPLAY_NAME "Gammu Library")
set(CPACK_COMPONENT_LIBRARY_GROUP "Runtime")
set(CPACK_COMPONENT_LIBRARY_INSTALL_TYPES "Standard;Developer;Full")
set(CPACK_COMPONENT_LIBRARY_REQUIRED "TRUE")
set(CPACK_COMPONENT_MANPAGES_DESCRIPTION "Manual pages for programs and configuration files.")
set(CPACK_COMPONENT_MANPAGES_DISPLAY_NAME "Manual Pages")
set(CPACK_COMPONENT_MANPAGES_GROUP "Documentation")
set(CPACK_COMPONENT_MANPAGES_INSTALL_TYPES "Standard;Developer;Full")
set(CPACK_COMPONENT_MANUAL_DESCRIPTION "User and Developer Manual")
set(CPACK_COMPONENT_MANUAL_DISPLAY_NAME "Gammu Manual")
set(CPACK_COMPONENT_MANUAL_GROUP "Documentation")
set(CPACK_COMPONENT_MANUAL_INSTALL_TYPES "Developer;Full")
set(CPACK_COMPONENT_MEDIA_DESCRIPTION "Various media files which can be used with Gammu.")
set(CPACK_COMPONENT_MEDIA_DISPLAY_NAME "Media Files")
set(CPACK_COMPONENT_MEDIA_GROUP "Documentation")
set(CPACK_COMPONENT_MEDIA_INSTALL_TYPES "Full")
set(CPACK_COMPONENT_PKGCONFIG_DEPENDS "headers")
set(CPACK_COMPONENT_PKGCONFIG_DESCRIPTION "Data for pkg-config program (automatic finding of compiler parameters for libraries).")
set(CPACK_COMPONENT_PKGCONFIG_DISPLAY_NAME "Pkg-config Data")
set(CPACK_COMPONENT_PKGCONFIG_GROUP "Development")
set(CPACK_COMPONENT_PKGCONFIG_INSTALL_TYPES "Developer;Full")
set(CPACK_COMPONENT_SMSD_DEPENDS "library")
set(CPACK_COMPONENT_SMSD_DESCRIPTION "Gammu SMS Daemon which automatically sends and receives messages.")
set(CPACK_COMPONENT_SMSD_DISPLAY_NAME "Gammu SMS Daemon")
set(CPACK_COMPONENT_SMSD_GROUP "Runtime")
set(CPACK_COMPONENT_SMSD_INSTALL_TYPES "Standard;Developer;Full")
set(CPACK_COMPONENT_SYMBIAN_DESCRIPTION "Applet for Symbian phones, install it to phone to communicate with them using Gammu.")
set(CPACK_COMPONENT_SYMBIAN_DISPLAY_NAME "Applet for Symbian Phones")
set(CPACK_COMPONENT_SYMBIAN_INSTALL_TYPES "Standard;Developer;Full")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_COMPONENT_UTILS_DEPENDS "gammu")
set(CPACK_COMPONENT_UTILS_DESCRIPTION "Utility scripts, mostly written using bourne shell, which you need to install on your own.")
set(CPACK_COMPONENT_UTILS_DISPLAY_NAME "Utility Scripts")
set(CPACK_COMPONENT_UTILS_GROUP "Runtime")
set(CPACK_COMPONENT_UTILS_INSTALL_TYPES "Full")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Gammu built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/runner/work/gammu/gammu/_build;Gammu;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/runner/work/gammu/gammu/cmake")
set(CPACK_NSIS_DISPLAY_NAME "Gammu 1.42.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "Gammu 1.42.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/runner/work/gammu/gammu/_build/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "Michal Čihař <michal@cihar.com>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/runner/work/gammu/gammu/installer/description.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Gammu All Mobile Management Utilities 1.42.0")
set(CPACK_PACKAGE_FILE_NAME "Gammu-1.42.0-Linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "Gammu 1.42.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "Gammu 1.42.0")
set(CPACK_PACKAGE_NAME "Gammu")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Michal Čihař")
set(CPACK_PACKAGE_VERSION "1.42.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "42")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/runner/work/gammu/gammu/installer/license.txt")
set(CPACK_RESOURCE_FILE_README "/home/runner/work/gammu/gammu/_build/readme.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/local/share/cmake-3.31/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_GROUP "Applications/Communications")
set(CPACK_RPM_PACKAGE_LICENSE "GPLv2")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/runner/work/gammu/gammu/_build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_STRIP_FILES "")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "gammu")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/runner/work/gammu/gammu/_build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
