# Adds flag to compiler if it supports it

macro (ADD_DLL _name _dir)
    if (WIN32)
        string (TOUPPER "${_name}" FLAGNAME)
        string (REPLACE " " "_" FLAGNAME "${FLAGNAME}")
        string (REPLACE "-" "_" FLAGNAME "${FLAGNAME}")
        string (REPLACE "=" "_" FLAGNAME "${FLAGNAME}")
        string (REPLACE "," "_" FLAGNAME "${FLAGNAME}")
        set (FLAGNAME "DLL_${FLAGNAME}")

        string(REGEX REPLACE "/[^/]*$" "" TMP_LIB_DIR "${_dir}")
        find_file(${FLAGNAME} "${_name}" "${TMP_LIB_DIR}/../bin/" "${TMP_LIB_DIR}") # DOC "Path to ${_name} library")
        list(APPEND WIN32_INSTALL_DLL "${${FLAGNAME}}")
        if (NOT ${FLAGNAME})
            message(FATAL_ERROR "Required runtime library ${_name} was not found near ${_dir}")
        endif()
        foreach(program_dir gammu gammu-detect tests tests/atgen smsd)
            configure_file("${${FLAGNAME}}" "${CMAKE_CURRENT_BINARY_DIR}/${program_dir}/${_name}" COPYONLY)
            foreach(config ${CMAKE_CONFIGURATION_TYPES})
                configure_file("${${FLAGNAME}}" "${CMAKE_CURRENT_BINARY_DIR}/${program_dir}/${config}/${_name}" COPYONLY)
            endforeach()
        endforeach()
    endif (WIN32)
endmacro (ADD_DLL _name _dir)
