# CMake generated Testfile for 
# Source directory: /home/runner/work/gammu/gammu/tests/atgen
# Build directory: /home/runner/work/gammu/gammu/_build/tests/atgen
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(is-memory-enabled "/home/runner/work/gammu/gammu/_build/tests/atgen/is-memory-enabled")
set_tests_properties(is-memory-enabled PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;18;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;35;atgen_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(is-memory-writeable "/home/runner/work/gammu/gammu/_build/tests/atgen/is-memory-writeable")
set_tests_properties(is-memory-writeable PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;18;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;36;atgen_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(set-requested-sms-memory "/home/runner/work/gammu/gammu/_build/tests/atgen/set-requested-sms-memory")
set_tests_properties(set-requested-sms-memory PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;18;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;37;atgen_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(deferred-event "/home/runner/work/gammu/gammu/_build/tests/atgen/deferred-event")
set_tests_properties(deferred-event PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;18;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;39;atgen_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(incoming-sms-info "/home/runner/work/gammu/gammu/_build/tests/atgen/incoming-sms-info")
set_tests_properties(incoming-sms-info PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;18;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;40;atgen_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(incoming-sms "/home/runner/work/gammu/gammu/_build/tests/atgen/incoming-sms")
set_tests_properties(incoming-sms PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;18;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;41;atgen_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(gsm-set-cnmi-params "/home/runner/work/gammu/gammu/_build/tests/atgen/gsm-set-cnmi-params")
set_tests_properties(gsm-set-cnmi-params PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;18;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;43;atgen_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(test-reply-get-cnmi "/home/runner/work/gammu/gammu/_build/tests/atgen/test-reply-get-cnmi")
set_tests_properties(test-reply-get-cnmi PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;18;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;44;atgen_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(get-sms-location "/home/runner/work/gammu/gammu/_build/tests/atgen/get-sms-location")
set_tests_properties(get-sms-location PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;18;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;45;atgen_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(get-sms "/home/runner/work/gammu/gammu/_build/tests/atgen/get-sms")
set_tests_properties(get-sms PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;18;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;46;atgen_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(test_sql_time "/home/runner/work/gammu/gammu/_build/tests/atgen/test_sql_time")
set_tests_properties(test_sql_time PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;25;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;49;smsd_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(smsd-incoming-cds "/home/runner/work/gammu/gammu/_build/tests/atgen/smsd-incoming-cds")
set_tests_properties(smsd-incoming-cds PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;25;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;52;smsd_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(smsd-cancel-call "/home/runner/work/gammu/gammu/_build/tests/atgen/smsd-cancel-call")
set_tests_properties(smsd-cancel-call PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;25;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;53;smsd_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(smsd-incoming-ussd "/home/runner/work/gammu/gammu/_build/tests/atgen/smsd-incoming-ussd")
set_tests_properties(smsd-incoming-ussd PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;25;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;54;smsd_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
add_test(smsd-1-folder-getnextsms "/home/runner/work/gammu/gammu/_build/tests/atgen/smsd-1-folder-getnextsms")
set_tests_properties(smsd-1-folder-getnextsms PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;25;add_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;55;smsd_test;/home/runner/work/gammu/gammu/tests/atgen/CMakeLists.txt;0;")
